from fpdf import FPDF

_UNICODE_REPLACE = {
    "\u2014": "-",  # em dash
    "\u2013": "-",  # en dash
    "\u2018": "'",  # left single quote
    "\u2019": "'",  # right single quote
    "\u201c": '"',  # left double quote
    "\u201d": '"',  # right double quote
    "\u2026": "...",  # ellipsis
    "\u2022": "*",  # bullet
    "\u00b2": "2",  # superscript 2
    "\u00b3": "3",  # superscript 3
    "\u2248": "~",  # approximately
    "\u2264": "<=",  # less than or equal
    "\u2265": ">=",  # greater than or equal
    "\u00b0": " deg",  # degree sign
    "\u0394": "Delta",  # Greek delta
    "\u2082": "2",  # subscript 2
    "\u2083": "3",  # subscript 3
    "\u00b5": "u",  # micro sign
}

def _sanitize(text: str) -> str:
    for k, v in _UNICODE_REPLACE.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class OfferPDF(FPDF):
    def __init__(self, title: str, doc_type: str):
        super().__init__()
        self.doc_title = title
        self.doc_type = doc_type
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, "ARCAMIND AI ENGINEERING", align="L")
        self.cell(0, 8, _sanitize(self.doc_type.upper() + " OFFER"), align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(123, 131, 235)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def add_title_page(self):
        self.add_page()
        self.ln(40)
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(40, 40, 40)
        self.cell(0, 15, _sanitize(self.doc_title), align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)
        self.set_font("Helvetica", "", 14)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, "Generated by Arcamind AI Engineering Platform", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(3)
        self.set_font("Helvetica", "", 11)
        self.cell(0, 8, "DRAFT - For Review Only", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(20)
        self.set_draw_color(123, 131, 235)
        self.set_line_width(1)
        self.line(60, self.get_y(), 150, self.get_y())

    def add_section(self, number: int, title: str, content: str, subsections: list[dict] | None = None):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(40, 40, 60)
        self.cell(0, 10, _sanitize(f"{number}. {title}"), new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        if content:
            self.set_font("Helvetica", "", 10)
            self.set_text_color(60, 60, 60)
            self.multi_cell(0, 5.5, _sanitize(content))
            self.ln(3)

        if subsections:
            for i, sub in enumerate(subsections):
                self.set_font("Helvetica", "B", 10)
                self.set_text_color(50, 50, 70)
                self.cell(0, 7, _sanitize(f"  {number}.{i+1} {sub['title']}"), new_x="LMARGIN", new_y="NEXT")
                self.set_font("Helvetica", "", 9.5)
                self.set_text_color(70, 70, 70)
                self.multi_cell(0, 5, _sanitize(f"    {sub['content']}"))
                self.ln(2)

        self.ln(3)


def generate_offer_pdf(doc_data: dict) -> bytes:
    """Generate a PDF from document data structure.

    doc_data should have: title, type, status, sections[]
    Each section: title, content, subsections?[{title, content}]
    """
    pdf = OfferPDF(doc_data.get("title", "Offer Document"), doc_data.get("type", "hardware"))
    pdf.alias_nb_pages()
    pdf.add_title_page()

    pdf.add_page()
    for i, section in enumerate(doc_data.get("sections", []), 1):
        pdf.add_section(
            number=i,
            title=section.get("title", ""),
            content=section.get("content", ""),
            subsections=section.get("subsections"),
        )

    return bytes(pdf.output())
